### ISSUE TITLE
你好，提示无法错误该怎么办

### ISSUE THREAD

**Issue by lisihai** [DeaglePC/CordCloud-Check-in#2]
root@OneCloud:~/CordCloud-Check-in# chmod +x cc_auto_check_in.sh
root@OneCloud:~/CordCloud-Check-in# ./cc_auto_check_in.sh
  File "cc_auto_check_in.py", line 13
    def __init__(self, config_file: str):
                                  ^
SyntaxError: invalid syntax
不懂Python。。

**Comment by DeaglePC** [comment]
升级python版本到3.6以上

**Comment by lisihai** [comment]
问题已解决，谢谢
